"""
guide_style.py — the one shared home for the house-style keys and the shade rule.

Not a command-line tool. It is imported by build_guide.py (renderer), export_geo.py
(map files), parse_guide_pdf.py (mode C: reading a guide back) and verify_guide.py.

Why one module: the PDF parser recognises a route name, a grade or a star rating by
its font size, colour and x-position. If the renderer's CSS drifts and the parser's
constants do not, the round trip silently breaks. So the parser-relevant CSS is
*generated* from the constants below (key_css()) and appended after guide.css by the
builder — change a value here and both sides move together.

Shade rule (F1): daylight D = [sunrise, sunset]; sun window W = [a, b] or none.
Shade S = D minus W = [sunrise, a) and (b, sunset]. Segments shorter than
MIN_SEGMENT_MIN are dropped; the longer remaining segment leads the phrase.
"""

import re

# ------------------------------------------------------------------ style keys (F6)
INK = 0x141414
WHITE = 0xFFFFFF
META = 0x767676        # first ascent / bolts line
NOTE = 0x9C3317        # hazard / route note
XREF = 0x3F6B3F        # the other source's reading
STAR = 0xC8442A        # star digit + ★, and the accent colour
NOSTAR = 0xBBBBBB      # unrated "—"
LENGTH = 0x555555
WALK = 0x777777        # "(Walking time: …)" in the approach heading
LOCAL = 0x4A4A4A       # local-script route name
DAGGER = 0x9A9A9A      # † after a reconstructed local name
FIELD = 0x4B2A78       # route-level field note
PICK = 0x6A3FA0        # top-pick symbol, field-notes box header

SZ_BADGE = 7.2         # white route-number badge
SZ_NAME = 8.2          # route name and grade (bold)
SZ_TITLE = 20.0        # sector title (bold)
SZ_SECTOR_NO = 15.0    # white sector number
SZ_H3 = 9.4            # prose heading (bold)
SZ_LEAD = 8.8          # sector intro paragraph
SZ_WARN = 7.8          # warning / field-notes box text
SZ_HEADLINE = 8.0      # shade bar under the sector header
SZ_LOCAL = 7.0
SZ_FIELD = 6.8

COLUMN_SPLIT_X = 300.0            # points; left column < split <= right column
COLUMN_ORIGINS = (40.0, 308.0)
GRADE_MIN_OFFSET = 150.0          # a bold 8.2 pt span this far into a column is the grade

# contents table: text colour of the bolt-status cell -> bolt_severity
SEVERITY_BY_COLOUR = {0xC8442A: 3, 0xB26A10: 2, 0x2F6B34: 0, 0x8A8A8A: 1}

HAZARD_WORDS = ('REBOLT', 'BAD BOLTING', 'RUN-OUT', 'RUNOUT', 'LOOSE ROCK',
                'BIRD NEST', 'DANGER')

APPENDIX_MARKER = 'APPENDIX'      # kicker of back pages; the parser stops routes there

# Every generated conditions paragraph contains this phrase. Mode C drops the
# paragraph that has it (it is regenerated) and keeps later ones as conditions_extra.
GENERATED_MARKER = 'Calculated, not observed'

# shade_override.kind: 'observed' (default) = a first-hand observation on a visit;
# 'source' = a conditions statement from a guidebook or database (e.g. "shade after 15:00
# in winter"). Same mechanics, different wording, so a database quote is never passed off
# as somebody's observation.
OVERRIDE_WORDS = {
    'observed': {'flag': 'calc., contradicted', 'tag': 'observed',
                 'calc': 'Calculation, contradicted by the observation above',
                 'note': 'a first-hand observation contradicted the calculation there'},
    'source':   {'flag': 'calc., superseded by source', 'tag': 'source',
                 'calc': 'Calculation, superseded by the source statement above',
                 'note': 'a guidebook or database states the shade there, and that statement '
                         'replaces the calculation'},
}


def override_words(sector):
    ov = sector.get('shade_override') or {}
    return OVERRIDE_WORDS.get(ov.get('kind', 'observed'), OVERRIDE_WORDS['observed'])

DEFAULT_TOP_PICK_SYMBOL = '♪'   # ♪
DEFAULT_TOP_PICK_LABEL = 'Top pick'

# Accepted spellings of local_src. Canonical values: "source" and "reconstructed".
LOCAL_SRC_ALIASES = {
    'source': 'source', 'sourced': 'source', 'book': 'source', 'guidebook': 'source',
    'sign': 'source', 'database': 'source',
    'reconstructed': 'reconstructed', 'translit': 'reconstructed',
    'transliterated': 'reconstructed',
}

TOP_PICK_ALIASES = ('top_pick', 'note')


def hexc(c):
    return '#%06x' % c


def key_css():
    """CSS for every element the PDF parser keys on. Appended after guide.css."""
    return """
/* ---- generated by guide_style.key_css(): parser keys, do not edit here ---- */
.rn { font-size: %(badge)spt; color: %(white)s; }
.rname { font-size: %(name)spt; font-weight: 700; color: %(ink)s; }
.rg { font-size: %(name)spt; font-weight: 700; color: %(ink)s; }
.rmeta { color: %(meta)s; }
.rnote { color: %(note)s; }
.rxref { color: %(xref)s; }
.st { color: %(star)s; }
.nost { color: %(nostar)s; }
.rl { color: %(length)s; }
.wt { color: %(walk)s; }
.rlocal { font-size: %(local)spt; color: %(localc)s; }
.dag { color: %(dag)s; }
.rfield { font-size: %(field)spt; color: %(fieldc)s; }
.pick { color: %(pick)s; }
.shead h1 { font-size: %(title)spt; font-weight: 700; }
.sbadge { font-size: %(secno)spt; color: %(white)s; }
.prose h3 { font-size: %(h3)spt; font-weight: 700; }
p.lead { font-size: %(lead)spt; }
.warn, .field { font-size: %(warn)spt; }
.shade { font-size: %(headline)spt; }
""" % dict(badge=SZ_BADGE, white=hexc(WHITE), name=SZ_NAME, ink=hexc(INK), meta=hexc(META),
           note=hexc(NOTE), xref=hexc(XREF), star=hexc(STAR), nostar=hexc(NOSTAR),
           length=hexc(LENGTH), walk=hexc(WALK), local=SZ_LOCAL, localc=hexc(LOCAL),
           dag=hexc(DAGGER), field=SZ_FIELD, fieldc=hexc(FIELD), pick=hexc(PICK),
           title=SZ_TITLE, secno=SZ_SECTOR_NO, h3=SZ_H3, lead=SZ_LEAD, warn=SZ_WARN,
           headline=SZ_HEADLINE)


# ------------------------------------------------------------------ data helpers

def local_src(route):
    v = route.get('local_src')
    if v is None:
        return None
    return LOCAL_SRC_ALIASES.get(str(v).lower(), str(v).lower())


def is_top_pick(route):
    return route.get('rating') in TOP_PICK_ALIASES


def month_label(meta):
    """'June' etc. From crag.month_label, else the month of conditions_date."""
    if meta.get('month_label'):
        return meta['month_label']
    d = meta.get('conditions_date') or (meta.get('conditions_meta') or {}).get('date')
    if d and re.match(r'\d{4}-\d{2}', d):
        names = ['January', 'February', 'March', 'April', 'May', 'June', 'July',
                 'August', 'September', 'October', 'November', 'December']
        return names[int(d[5:7]) - 1]
    return 'Conditions'


# ------------------------------------------------------------------ shade (F1)

MIN_SEGMENT_MIN = 15
DEFAULT_SUNRISE, DEFAULT_SUNSET = '06:00', '20:00'


def to_min(hhmm):
    h, m = hhmm.split(':')
    return int(h) * 60 + int(m)


def daylight(meta):
    cm = (meta or {}).get('conditions_meta') or {}
    return (cm.get('sunrise') or DEFAULT_SUNRISE, cm.get('sunset') or DEFAULT_SUNSET)


def shade_segments(sun, sunrise, sunset):
    """
    Return a list of (kind, start, end, minutes) shade segments inside daylight,
    kind in {'before', 'after', 'all'}; sorted longest first; short ones dropped.
    """
    if not sun:
        return [('all', sunrise, sunset, to_min(sunset) - to_min(sunrise))]
    a, b = sun
    segs = []
    before = to_min(a) - to_min(sunrise)
    after = to_min(sunset) - to_min(b)
    if before >= MIN_SEGMENT_MIN:
        segs.append(('before', sunrise, a, before))
    if after >= MIN_SEGMENT_MIN:
        segs.append(('after', b, sunset, after))
    segs.sort(key=lambda s: -s[3])
    return segs


def shade_parts(sun, sunrise, sunset):
    """
    (main, other) phrases. Main: 'until 09:00' / 'after 13:00' / 'all day'.
    Other (the shorter segment): 'before 09:00' / 'after 18:00' / None.
    (None, None) when neither segment reaches MIN_SEGMENT_MIN.
    """
    segs = shade_segments(sun, sunrise, sunset)
    if not segs:
        return None, None
    words = []
    for i, (kind, start, end, _) in enumerate(segs):
        if kind == 'all':
            words.append('all day')
        elif kind == 'before':
            words.append(('until %s' if i == 0 else 'before %s') % end)
        else:
            words.append('after %s' % start)
    return words[0], (words[1] if len(words) > 1 else None)


def shade_headline(sector, meta):
    """The sector header phrase. Always contains the word 'Shade'."""
    if sector.get('shade_override'):
        return sector['shade_override']['headline']
    main, other = shade_parts(sector.get('sun'), *daylight(meta))
    if main is None:
        return 'Shade: hardly any (sunlit about %s–%s)' % tuple(sector['sun'])
    if main == 'all day':
        return 'Shade all day'
    return 'Shade (climbable) %s%s' % (main, (' · also %s' % other) if other else '')


def shade_table(sector, meta):
    """Contents-table cell (HTML)."""
    if sector.get('shade_override'):
        return sector['shade_override']['table']
    main, other = shade_parts(sector.get('sun'), *daylight(meta))
    if main is None:
        return 'hardly any'
    if main == 'all day':
        return 'all day'
    return '<b>%s</b>%s' % (main, ('<div class="tgr">also %s</div>' % other) if other else '')


def shade_short(sector, meta):
    """Coordinate-table cell (HTML)."""
    if sector.get('shade_override'):
        return sector['shade_override']['short']
    main, other = shade_parts(sector.get('sun'), *daylight(meta))
    if main is None:
        return 'hardly any'
    if main == 'all day':
        return 'all day'
    return main + (("<br><span class='small'>also %s</span>" % other) if other else '')


def shade_text(sector, meta):
    """Plain text for KML/GPX/CSV."""
    if sector.get('shade_override'):
        return strip_tags(sector['shade_override'].get('short', sector['shade_override']['headline']))
    main, other = shade_parts(sector.get('sun'), *daylight(meta))
    if main is None:
        return 'shade: hardly any'
    if main == 'all day':
        return 'shade all day'
    return 'shade %s%s' % (main, (', and %s' % other) if other else '')


def strip_tags(s):
    s = re.sub(r'<br\s*/?>', ' ', s or '')
    return re.sub(r'\s+', ' ', re.sub(r'<[^>]+>', '', s)).strip()
